export type RuntimeType = 'docker' | 'microvm' | 'local'
export type ExecutionStatus = 'queued' | 'running' | 'success' | 'failed' | 'timeout'

export interface ExecutionRequest {
  id?: string // Generated by API if not provided
  sessionId?: string // Associated session ID
  command: string
  runtime: RuntimeType
  cpuLimit?: number // CPU cores, default 1
  memoryLimitMB?: number // Memory in MB, default 512
  timeoutSeconds?: number // Timeout in seconds, default 30
  allowNetwork?: boolean // Network access, default false
  allowFilesystemWrite?: boolean // Filesystem write, default false
  limits?: {
    cpu: number
    memory: number
    timeout: number
  }
  network?: boolean
  filesystemAccess?: string[]
}

export interface ExecutionResult {
  id: string
  sessionId?: string
  command: string
  runtime: RuntimeType
  status: ExecutionStatus
  stdout: string
  stderr: string
  exitCode: number
  duration: number
  timestamp: string
  startedAt?: string
  completedAt?: string
  riskLevel: 'low' | 'medium' | 'high'
}

export interface StreamChunk {
  type: 'stdout' | 'stderr' | 'exit'
  data: string
  timestamp: number
}
